export const FETCH_COUNCLILLORS = Symbol('FETCH_COUNCLILLORS');
export const FETCH_COUNCLILLORS_SUCCESS = Symbol('FETCH_COUNCLILLORS_SUCCESS');
export const FETCH_COUNCLILLORS_FAILURE = Symbol('FETCH_COUNCLILLORS_FAILURE');
