export const FETCH_COUNCLILS = Symbol('FETCH_COUNCLILS');
export const FETCH_COUNCLILS_SUCCESS = Symbol('FETCH_COUNCLILS_SUCCESS');
export const FETCH_COUNCLILS_FAILURE = Symbol('FETCH_COUNCLILS_FAILURE');
